# This file was generated by GoReleaser. DO NOT EDIT.
cask "pdp-cli" do
  name "pdp-cli"
  desc "CLI for Discovery 2.x"
  homepage "https://github.com/diego-granados/pdp-cli-releases-test"
  version "0.2.0-beta9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "discovery"

  on_macos do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_amd64.tar.gz"
      sha256 "13f5b98c7104f489a1115b3cdbf76ee62023b23de72aa21f39e3efe3d5b1cfe1"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_darwin_arm64.tar.gz"
      sha256 "47d5ed96b1f72c8a87d28a2b28a17a634ce56e97d6ba8ea87036bdab1f8104fe"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_amd64.tar.gz"
      sha256 "cd73eb1b03f6dba005db9fd991d0cec68342aa853375d710e144d8c85f6efd70"
    end
    on_arm do
      url "https://github.com/diegogranados-pi/pdp-cli-releases-test/releases/download/v#{version}/pdp-cli-releases-test_#{version}_linux_arm64.tar.gz"
      sha256 "9dfd0957f685c744d1e20e709553e21bd6bf0c6be8268182c715afb1fbc9d809"
    end
  end

  # No zap stanza required
end
